server:
  port: 7002
  servlet:
    context-path: /mall-tiny-02
spring:
  datasource:
    url: jdbc:mysql://124.221.249.213:3306/mall_learning?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: myk522326

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
